import { Link, useRouter } from 'expo-router';
import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { BrandLogo } from '@/components/brand-logo';
import { PrimaryButton } from '@/components/primary-button';
import { AppScreen } from '@/components/screen';
import { useAuth } from '@/providers/auth-provider';
import { colors, spacing, typography } from '@/theme/tokens';

export default function LoginScreen() {
  const router = useRouter(); const { signIn } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  async function submit() { setError(null); if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) return setError('Enter a valid email address.'); if (!password) return setError('Enter your password.'); setSubmitting(true); try { await signIn(email, password); router.replace('/' as never); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to sign in right now.'); } finally { setSubmitting(false); } }
  return <AppScreen><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><BrandLogo style={styles.logo} /><Text style={styles.eyebrow}>WELCOME BACK</Text><Text style={styles.title}>Sign in to Tixora</Text><Text style={styles.copy}>Access your account while we build the mobile ticket experience.</Text><View style={styles.form}><Text style={styles.label}>Email</Text><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="you@email.com" placeholderTextColor={colors.mutedForeground} style={styles.input} value={email} onChangeText={setEmail} /><Text style={styles.label}>Password</Text><TextInput autoComplete="current-password" placeholder="Your password" placeholderTextColor={colors.mutedForeground} secureTextEntry style={styles.input} value={password} onChangeText={setPassword} onSubmitEditing={submit} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton label={submitting ? 'Signing in…' : 'Sign in'} disabled={submitting} onPress={submit} /></View><Text style={styles.footer}>New to Tixora? <Link href={'/register' as never} style={styles.link}>Create an account</Link></Text></ScrollView></AppScreen>;
}
const styles = StyleSheet.create({ content: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: spacing.lg, paddingVertical: spacing.xxl }, logo: { alignSelf: 'center', marginBottom: spacing.xxl }, eyebrow: { color: colors.primary, fontSize: typography.eyebrow, fontWeight: '800', letterSpacing: 1.5 }, title: { color: colors.foreground, fontSize: typography.display, fontWeight: '800', marginTop: spacing.sm }, copy: { color: colors.mutedForeground, fontSize: typography.body, lineHeight: 22, marginTop: spacing.sm }, form: { gap: spacing.sm, marginTop: spacing.xl }, label: { color: colors.foreground, fontSize: typography.label, fontWeight: '700', marginTop: spacing.sm }, input: { backgroundColor: colors.card, borderColor: colors.border, borderRadius: 12, borderWidth: 1, color: colors.foreground, fontSize: typography.body, height: 52, paddingHorizontal: spacing.md }, error: { color: colors.destructive, fontSize: typography.label, marginTop: spacing.sm }, footer: { color: colors.mutedForeground, fontSize: typography.body, marginTop: spacing.xl, textAlign: 'center' }, link: { color: colors.primary, fontWeight: '800' } });
