import { Link, useRouter } from 'expo-router';
import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { BrandLogo } from '@/components/brand-logo';
import { PrimaryButton } from '@/components/primary-button';
import { AppScreen } from '@/components/screen';
import { useAuth } from '@/providers/auth-provider';
import { colors, spacing, typography } from '@/theme/tokens';

export default function RegisterScreen() {
  const router = useRouter(); const { signUp } = useAuth(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  async function submit() { setError(null); if (name.trim().length < 2) return setError('Enter your full name.'); if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) return setError('Enter a valid email address.'); if (password.length < 8) return setError('Password must be at least 8 characters.'); if (password !== confirmation) return setError('Passwords do not match.'); setSubmitting(true); try { await signUp(name, email, password, confirmation); router.replace('/' as never); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create your account.'); } finally { setSubmitting(false); } }
  return <AppScreen><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><BrandLogo style={styles.logo} /><Text style={styles.eyebrow}>JOIN TIXORA</Text><Text style={styles.title}>Create account</Text><Text style={styles.copy}>Book faster and keep your account in one place.</Text><View style={styles.form}><Field label="Full name" value={name} onChangeText={setName} placeholder="Juan Dela Cruz" autoComplete="name" /><Field label="Email" value={email} onChangeText={setEmail} placeholder="you@email.com" autoComplete="email" keyboardType="email-address" /><Field label="Password" value={password} onChangeText={setPassword} placeholder="At least 8 characters" autoComplete="new-password" secureTextEntry /><Field label="Confirm password" value={confirmation} onChangeText={setConfirmation} placeholder="Repeat your password" autoComplete="new-password" secureTextEntry />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<PrimaryButton label={submitting ? 'Creating account…' : 'Create account'} disabled={submitting} onPress={submit} /></View><Text style={styles.footer}>Already have an account? <Link href={'/login' as never} style={styles.link}>Sign in</Link></Text></ScrollView></AppScreen>;
}
function Field(props: { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; autoComplete: 'name' | 'email' | 'new-password'; secureTextEntry?: boolean; keyboardType?: 'email-address' }) { return <View style={styles.field}><Text style={styles.label}>{props.label}</Text><TextInput autoCapitalize="none" autoComplete={props.autoComplete} keyboardType={props.keyboardType} placeholder={props.placeholder} placeholderTextColor={colors.mutedForeground} secureTextEntry={props.secureTextEntry} style={styles.input} value={props.value} onChangeText={props.onChangeText} /></View>; }
const styles = StyleSheet.create({ content: { paddingHorizontal: spacing.lg, paddingVertical: spacing.xl }, logo: { alignSelf: 'center', marginBottom: spacing.xl }, eyebrow: { color: colors.primary, fontSize: typography.eyebrow, fontWeight: '800', letterSpacing: 1.5 }, title: { color: colors.foreground, fontSize: typography.display, fontWeight: '800', marginTop: spacing.sm }, copy: { color: colors.mutedForeground, fontSize: typography.body, lineHeight: 22, marginTop: spacing.sm }, form: { gap: spacing.sm, marginTop: spacing.xl }, field: { gap: spacing.sm }, label: { color: colors.foreground, fontSize: typography.label, fontWeight: '700', marginTop: spacing.sm }, input: { backgroundColor: colors.card, borderColor: colors.border, borderRadius: 12, borderWidth: 1, color: colors.foreground, fontSize: typography.body, height: 52, paddingHorizontal: spacing.md }, error: { color: colors.destructive, fontSize: typography.label, marginTop: spacing.sm }, footer: { color: colors.mutedForeground, fontSize: typography.body, marginTop: spacing.xl, textAlign: 'center' }, link: { color: colors.primary, fontWeight: '800' } });
