import { useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ImageBackground, ScrollView, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { EventCard } from '@/components/event-card';
import { AppScreen } from '@/components/screen';
import { LoadingState, MessageState } from '@/components/state-view';
import { categories, fetchEvents, type EventCategory, type TixEvent } from '@/lib/events';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function DiscoverScreen() {
  const router = useRouter();
  const [query, setQuery] = useState(''); const [category, setCategory] = useState<EventCategory | undefined>(); const [events, setEvents] = useState<TixEvent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(false); try { setEvents(await fetchEvents({ q: query.trim() || undefined, category })); } catch { setError(true); } finally { setLoading(false); } }, [category, query]);
  // Debouncing keeps the existing API search responsive without firing on each keypress.
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  if (loading && events.length === 0) return <AppScreen><LoadingState label="Loading events…" /></AppScreen>;
  if (error) return <AppScreen><MessageState title="Couldn’t load the catalog" detail="Make sure the Laravel API is available, then try again." actionLabel="Try again" onAction={() => void load()} /></AppScreen>;
  const moviePosters = events.filter((event) => event.category === 'Movies' && !!event.image);
  return <AppScreen><FlatList data={events} keyExtractor={(item) => item.slug} contentContainerStyle={styles.list} ListHeaderComponent={<><Text style={styles.title}>Discover</Text><Text style={styles.copy}>Concerts, movies, and events in one place.</Text><CinemaCarousel movies={moviePosters} onOpen={(slug) => router.push(`/cinema/${slug}` as never)} onBrowse={() => router.push('/cinema' as never)} /><TextInput autoCapitalize="none" onChangeText={setQuery} placeholder="Search events, venues, artists…" placeholderTextColor={colors.mutedForeground} style={styles.input} value={query} /><View style={styles.chips}><Chip active={!category} label="All" onPress={() => setCategory(undefined)} />{categories.map((item) => <Chip active={category === item} key={item} label={item} onPress={() => setCategory(item)} />)}</View><Text style={styles.count}>{events.length} {events.length === 1 ? 'event' : 'events'} available</Text></>} renderItem={({ item }) => <EventCard event={item} onPress={() => router.push((item.category === 'Movies' ? `/cinema/${item.slug}` : `/events/${item.slug}`) as never)} />} ItemSeparatorComponent={() => <View style={{ height: spacing.md }} />} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No events matched your search.</Text><Text style={styles.emptyCopy}>Try a different artist, venue, or category.</Text></View>} /></AppScreen>;
}
function Chip({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text></Pressable>; }
function CinemaCarousel({ movies, onOpen, onBrowse }: { movies: TixEvent[]; onOpen: (slug: string) => void; onBrowse: () => void }) {
  if (!movies.length) return <Pressable accessibilityRole="button" onPress={onBrowse} style={styles.cinemaFallback}><View><Text style={styles.cinemaEyebrow}>TIXORA CINEMA</Text><Text style={styles.cinemaTitle}>Browse movies</Text><Text style={styles.cinemaCopy}>Movie posters will appear here when the catalog provides them.</Text></View><Text style={styles.cinemaArrow}>→</Text></Pressable>;
  return <View style={styles.cinemaWrap}><ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false} snapToInterval={272} decelerationRate="fast" contentContainerStyle={styles.cinemaScroller}>{movies.map((movie) => <Pressable accessibilityRole="button" accessibilityLabel={`View ${movie.title}`} key={movie.slug} onPress={() => onOpen(movie.slug)} style={styles.cinemaSlide}><ImageBackground source={{ uri: movie.image! }} imageStyle={styles.cinemaImage} style={styles.cinemaImage}><View style={styles.cinemaOverlay}><Text style={styles.cinemaEyebrow}>TIXORA CINEMA</Text><Text numberOfLines={2} style={styles.cinemaTitle}>{movie.title}</Text><Text style={styles.cinemaAction}>Browse movie →</Text></View></ImageBackground></Pressable>)}</ScrollView></View>;
}
const styles = StyleSheet.create({ list: { padding: spacing.lg, paddingBottom: spacing.xxl }, title: { color: colors.foreground, fontSize: 28, fontWeight: '800' }, copy: { color: colors.mutedForeground, fontSize: typography.body, marginTop: spacing.xs }, cinemaWrap: { marginTop: spacing.lg, marginHorizontal: -spacing.lg }, cinemaScroller: { gap: spacing.md, paddingHorizontal: spacing.lg }, cinemaSlide: { height: 176, width: 272 }, cinemaImage: { flex: 1, justifyContent: 'flex-end' }, cinemaOverlay: { backgroundColor: 'rgba(75, 8, 20, 0.70)', flex: 1, justifyContent: 'flex-end', padding: spacing.md }, cinemaFallback: { alignItems: 'center', backgroundColor: colors.primaryDeep, borderRadius: radius.md, flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.lg, padding: spacing.md }, cinemaEyebrow: { color: '#FFDADF', fontSize: typography.eyebrow, fontWeight: '800', letterSpacing: 1 }, cinemaTitle: { color: colors.white, fontSize: typography.title, fontWeight: '800', marginTop: spacing.xs }, cinemaCopy: { color: '#FFDADF', fontSize: 13, lineHeight: 18, marginTop: spacing.xs }, cinemaAction: { color: colors.white, fontSize: typography.label, fontWeight: '800', marginTop: spacing.sm }, cinemaArrow: { color: colors.white, fontSize: 28, fontWeight: '800' }, input: { backgroundColor: colors.muted, borderRadius: radius.md, color: colors.foreground, fontSize: typography.body, height: 50, marginTop: spacing.lg, paddingHorizontal: spacing.md }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md }, chip: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, chipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.mutedForeground, fontSize: typography.label, fontWeight: '700' }, chipTextActive: { color: colors.white }, count: { color: colors.mutedForeground, fontSize: typography.label, marginVertical: spacing.lg }, empty: { backgroundColor: colors.secondary, borderRadius: radius.md, padding: spacing.lg }, emptyTitle: { color: colors.foreground, fontSize: typography.body, fontWeight: '800' }, emptyCopy: { color: colors.mutedForeground, lineHeight: 20, marginTop: spacing.xs } });
