import { useCallback, useEffect, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { EventCard } from '@/components/event-card';
import { AppScreen } from '@/components/screen';
import { LoadingState, MessageState } from '@/components/state-view';
import { categories, fetchEvents, type EventCategory, type TixEvent } from '@/lib/events';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function DiscoverScreen() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState<EventCategory | undefined>(); const [events, setEvents] = useState<TixEvent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(false); try { setEvents(await fetchEvents({ q: query.trim() || undefined, category })); } catch { setError(true); } finally { setLoading(false); } }, [category, query]);
  // Debouncing keeps the existing API search responsive without firing on each keypress.
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  if (loading && events.length === 0) return <AppScreen><LoadingState label="Loading events…" /></AppScreen>;
  if (error) return <AppScreen><MessageState title="Couldn’t load the catalog" detail="Make sure the Laravel API is available, then try again." actionLabel="Try again" onAction={() => void load()} /></AppScreen>;
  return <AppScreen><FlatList data={events} keyExtractor={(item) => item.slug} contentContainerStyle={styles.list} ListHeaderComponent={<><Text style={styles.title}>Discover</Text><Text style={styles.copy}>Concerts, movies, and events in one place.</Text><TextInput autoCapitalize="none" onChangeText={setQuery} placeholder="Search events, venues, artists…" placeholderTextColor={colors.mutedForeground} style={styles.input} value={query} /><View style={styles.chips}><Chip active={!category} label="All" onPress={() => setCategory(undefined)} />{categories.map((item) => <Chip active={category === item} key={item} label={item} onPress={() => setCategory(item)} />)}</View><Text style={styles.count}>{events.length} {events.length === 1 ? 'event' : 'events'} available</Text></>} renderItem={({ item }) => <EventCard event={item} />} ItemSeparatorComponent={() => <View style={{ height: spacing.md }} />} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No events matched your search.</Text><Text style={styles.emptyCopy}>Try a different artist, venue, or category.</Text></View>} /></AppScreen>;
}
function Chip({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ list: { padding: spacing.lg, paddingBottom: spacing.xxl }, title: { color: colors.foreground, fontSize: typography.display, fontWeight: '800' }, copy: { color: colors.mutedForeground, fontSize: typography.body, marginTop: spacing.xs }, input: { backgroundColor: colors.muted, borderRadius: radius.md, color: colors.foreground, fontSize: typography.body, height: 50, marginTop: spacing.lg, paddingHorizontal: spacing.md }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md }, chip: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, chipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.mutedForeground, fontSize: typography.label, fontWeight: '700' }, chipTextActive: { color: colors.white }, count: { color: colors.mutedForeground, fontSize: typography.label, marginVertical: spacing.lg }, empty: { backgroundColor: colors.secondary, borderRadius: radius.md, padding: spacing.lg }, emptyTitle: { color: colors.foreground, fontSize: typography.body, fontWeight: '800' }, emptyCopy: { color: colors.mutedForeground, lineHeight: 20, marginTop: spacing.xs } });
