import { useRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { BrandLogo } from '@/components/brand-logo';
import { EventCard } from '@/components/event-card';
import { AppScreen } from '@/components/screen';
import { LoadingState, MessageState } from '@/components/state-view';
import { fetchEvents, type TixEvent } from '@/lib/events';
import { useAuth } from '@/providers/auth-provider';
import { colors, radius, spacing, typography } from '@/theme/tokens';

export default function HomeScreen() {
  const router = useRouter(); const { session } = useAuth(); const [events, setEvents] = useState<TixEvent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(false); try { const data = await fetchEvents({ limit: 4 }); setEvents(data); } catch { setError(true); } finally { setLoading(false); } }, []);
  // The initial request belongs to the screen lifecycle; later requests use the explicit retry control.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  if (loading) return <AppScreen><LoadingState label="Finding events near you…" /></AppScreen>;
  if (error) return <AppScreen><MessageState title="Couldn’t load events" detail="Check that the Laravel API is running and your mobile API URL is configured." actionLabel="Try again" onAction={() => void load()} /></AppScreen>;
  return <AppScreen><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.top}><BrandLogo /><Pressable accessibilityRole="button" onPress={() => router.push('/account' as never)} style={styles.avatar}><Text style={styles.avatarText}>{session?.user.name.slice(0, 1).toUpperCase()}</Text></Pressable></View><Text style={styles.greeting}>Hello, {session?.user.name.split(' ')[0]}.</Text><Text style={styles.subhead}>Your next night out starts here.</Text><Pressable onPress={() => router.push('/discover' as never)} style={styles.search}><Text style={styles.searchIcon}>⌕</Text><Text style={styles.searchText}>Search events, venues, artists…</Text></Pressable><View style={styles.hero}><Text style={styles.eyebrow}>OFFICIAL TICKETING</Text><Text style={styles.heroTitle}>Discover live{`\n`}moments near you.</Text><Pressable onPress={() => router.push('/discover' as never)} style={styles.heroButton}><Text style={styles.heroButtonText}>Explore events</Text></Pressable></View><View style={styles.sectionHead}><Text style={styles.section}>Trending this month</Text><Pressable onPress={() => router.push('/discover' as never)}><Text style={styles.viewAll}>View all</Text></Pressable></View>{events.length ? <View style={styles.list}>{events.map((event) => <EventCard event={event} key={event.slug} onPress={() => router.push('/discover' as never)} />)}</View> : <View style={styles.empty}><Text style={styles.emptyTitle}>No events available yet</Text><Text style={styles.emptyCopy}>Check back once the catalog has events to show.</Text></View>}</ScrollView></AppScreen>;
}
const styles = StyleSheet.create({ content: { padding: spacing.lg, paddingBottom: spacing.xxl }, top: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, avatar: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: radius.pill, height: 42, justifyContent: 'center', width: 42 }, avatarText: { color: colors.primary, fontWeight: '800' }, greeting: { color: colors.foreground, fontSize: typography.title, fontWeight: '800', marginTop: spacing.xl }, subhead: { color: colors.mutedForeground, fontSize: typography.body, marginTop: spacing.xs }, search: { alignItems: 'center', backgroundColor: colors.muted, borderRadius: radius.md, flexDirection: 'row', gap: spacing.sm, height: 50, marginTop: spacing.lg, paddingHorizontal: spacing.md }, searchIcon: { color: colors.mutedForeground, fontSize: 24 }, searchText: { color: colors.mutedForeground, fontSize: typography.label }, hero: { backgroundColor: colors.primaryDeep, borderRadius: radius.lg, marginTop: spacing.lg, overflow: 'hidden', padding: spacing.lg }, eyebrow: { color: '#FFDADF', fontSize: typography.eyebrow, fontWeight: '800', letterSpacing: 1.3 }, heroTitle: { color: colors.white, fontSize: 30, fontWeight: '800', lineHeight: 35, marginTop: spacing.sm }, heroButton: { alignSelf: 'flex-start', backgroundColor: colors.white, borderRadius: radius.sm, marginTop: spacing.lg, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, heroButtonText: { color: colors.primaryDeep, fontSize: typography.label, fontWeight: '800' }, sectionHead: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xl }, section: { color: colors.foreground, fontSize: typography.title, fontWeight: '800' }, viewAll: { color: colors.primary, fontSize: typography.label, fontWeight: '800' }, list: { gap: spacing.md, marginTop: spacing.md }, empty: { backgroundColor: colors.secondary, borderRadius: radius.md, marginTop: spacing.md, padding: spacing.lg }, emptyTitle: { color: colors.foreground, fontSize: typography.body, fontWeight: '800' }, emptyCopy: { color: colors.mutedForeground, lineHeight: 20, marginTop: spacing.xs } });
